#!/usr/bin/env python3
"""
Build surname ground truth corpus from multiple web sources.
Scrapes caste-specific surname lists with URL attribution.

Output: data/surname_ground_truth.csv
Columns: surname, caste, source_url, gothram, region, example_full_names
"""
import csv
import json
import os
import time
from collections import defaultdict

# ─── Ground Truth Data ───────────────────────────────────────────────────────
# Each entry: (caste, source_url, surnames_list, region)
# Surnames are added programmatically from web scraping results

CORPUS = []  # Will be populated below


def add_source(caste, url, surnames_str, region="Krishna-Guntur, AP"):
    """Add a batch of surnames from one source."""
    surnames = [s.strip().upper() for s in surnames_str.split(',') if s.strip()]
    for s in surnames:
        # Skip multi-word entries that aren't surnames
        if len(s) > 30 or ' ' in s.strip():
            continue
        CORPUS.append({
            'surname': s,
            'caste': caste,
            'source_url': url,
            'gothram': '',
            'region': region,
        })


# ═══════════════════════════════════════════════════════════════════════════
# KAMMA SOURCES
# ═══════════════════════════════════════════════════════════════════════════

# Source 1: kammaschowdary.blogspot.com (already scraped, 2207 surnames)
# Loaded from our existing match_kamma.py data
kamma_file = os.path.join('archives', 'match_kamma.py')
if os.path.exists(kamma_file):
    with open(kamma_file) as f:
        content = f.read()
    start = content.find('kamma_web_raw = """') + len('kamma_web_raw = """')
    end = content.find('"""', start)
    kamma_raw = content[start:end]
    add_source('Kamma', 'https://kammaschowdary.blogspot.com/p/kammas-surnames-and-gothrams.html',
               ','.join(kamma_raw.split()), 'Andhra Pradesh')

# Source 2: kammabidda.weebly.com
add_source('Kamma', 'https://kammabidda.weebly.com/surnames--villages.html',
    'ABBINENI,ABBURU,ACHANTA,ADUSUMALLI,ALAPATI,ALLURU,ALURU,AMBATI,ARAVAPALLI,AREKATLA,AREMANDA,AREPALLI,ATLURU,ATTALURI,ATTOTA,AVULA,BALANENI,BALUSU,BANDARUPALLI,BANDI,BANDLAMUDI,BATHINA,BEJAWADA,BELLAM,BELLAMKONDA,BHEEMINENI,BIKKASANI,BODAPATI,BODDU,BODDULURU,BODI,BOGOLU,BOLLINENI,BONDALAPATI,BOPPUDI,BOYAPATI,CHADALAVADA,CHALLA,CHALLAPALLI,CHAMALLAMUDI,CHAPALAMADUGU,CHAVA,CHEBROLU,CHEKURU,CHENNUPATI,CHERUKURU,CHIGURUPATI,CHILAKAPATI,CHILUKURI,CHIRUMAMILLA,CHITTURU,CHUKKAPALLI,CHUNDI,DAGGUMALLI,DAMA,DAMACHERLA,DAMMALAPATI,DANDAMUDI,DAVULURU,DHULIPALLA,DONDAPATI,DONEPUDI,DOPPALAPUDI,DUGGIRALA,EDARA,EDUPUGANTI,GADDE,GADDIPATI,GALLA,GANGAVARAPU,GANGINENI,GARIKAPATI,GAVINI,GINJUPALLI,GOGINENI,GONUGUNTLA,GORANTLA,GOTTIMUKKALA,GOTTIPATI,GOVADA,GUDAPATI,GUDAVALLI,GULLAPALLI,GUNTUPALLI,GUTHIKONDA,INAGANTI,INAMPUDI,INAVOLU,INTURI,JAGARLAMUDI,JAMPALA,JASTI,JONNALAGADDA,KADIYALA,KAKANI,KAKARLA,KAKUMANU,KAMBAMPATI,KAMEPALLI,KAMINENI,KANAGALA,KANCHARLA,KANKANALA,KANTHETI,KANURI,KARANAM,KARLAPUDI,KARUMANCHI,KASARANENI,KATRAGADDA,KAVURU,KAZA,KESINENI,KODALI,KOGANTI,KOLLA,KOLLI,KOLLIPARA,KOMATINENI,KOMMALAPATI,KOMMINENI,KONDAPALLI,KONDAVEETI,KONERU,KORRAPATI,KOTAPATI,KOTHAPALLI,KOVELAMUDI,KUCHIPUDI,KUDARAVALLI,KURAPATI,LAGADAPATI,LANKA,LINGAMANENI,MADAMANCHI,MADDINENI,MADDIPATI,MADDIPATLA,MADDUKURU,MAGANTI,MALEMPATI,MALINENI,MALLADI,MALLAMPATI,MANDAVA,MANNAM,MANNAVA,MEKA,MIKKILINENI,MOTURI,MOVVA,MUKKAMALA,MULPURI,MUNAGALA,MULLAPUDI,MUPPALLA,MUPPAVARAPU,MUSUNURI,MYNAMPATI,MYNENI,NADELLA,NALLAMOTHU,NALLAPATI,NALLURI,NAMBURI,NANDAMURI,NANDIGAM,NARA,NARLA,NARNE,NARRA,NEERUKONDA,NIMMAGADDA,NUTHAKKI,NUTHALAPATI,PAKALAPATI,PALADUGU,PAMIDI,PAMULAPATI,PAPINENI,PARIMI,PARITALA,PARUCHURI,PATIBANDLA,PATTIPATI,PAVULURI,PENDYALA,PERAVALI,POLAVARAPU,POLINENI,POPURI,POTHINENI,POTLURI,PUCHAKAYALA,PULIPATI,PUNUKOLLU,PUTTAGUNTA,PUVVADA,RALLAPALLI,RAVELLA,RAVURI,RAYAPATI,SADINENI,SAJJA,SAKHAMURI,SANKURATRI,SINGAMANENI,SOMPALLI,SUNKARA,SURAPANENI,TADIKONDA,TALLURI,THOTTEMPUDI,TIRUVEEDHULA,UNDAVALLI,UNNAM,UPPALAPATI,VADDE,VADDINENI,VADLAMUDI,VADLAPATLA,VALLURI,VANKAYALAPATI,VEERAMANCHINENI,VEERAPANENI,VEEREPALLI,VELAGAPUDI,VELIVOLU,VELLANKI,VEMULAPALLI,VEMURI,VENIGALLA,VIPPARLA,YADLAPATI,YALAMANCHILI,YALAVARTHI,YANAMADALA,YARLAGADDA,YELETI,YELLANKI,YEMINENI',
    'Krishna-Guntur, AP')


# ═══════════════════════════════════════════════════════════════════════════
# REDDY SOURCES
# ═══════════════════════════════════════════════════════════════════════════

# Source 1: reddyjanasangham.blogspot.com
add_source('Reddy', 'http://reddyjanasangham.blogspot.com/2012/11/reddy-surnames-and-gothrams.html',
    'AALURI,ABBIDI,ABBIREDDY,ADLA,ADMA,AEMALLA,AGUMAAMIDI,AIREDDY,AILENI,AKAVARAM,AKARAPU,AKKAPALLI,AKKATI,ALAVALA,ALLA,ALLADA,ALETI,ALLAM,AMBATI,AMARAM,ANANTULA,ANDEM,ANGANAGARI,ANIREDDY,ANKIREDDY,ANNADI,ANNAPAREDDY,ANNAREDDY,ANUMANDLA,ANUMULA,ANUPATI,APPANNAGARI,ARIMANDA,ARUMALLA,ARUTLA,ASI,ATLA,AVALA,AVUTHU,BACHALA,BACHCHU,BAIRU,BAGGANI,BAJJURI,BANDA,BANDARI,BANDI,BANKA,BASANGARI,BASA,BATTEPATI,BATTU,BEDADALA,BEEMIREDDY,BEERAVOLU,BEERAM,BENDRAM,BELAGANTI,BETHI,BEKKEM,BHANURI,BHEEMAVARAPU,BHIMAVARAPU,BHIMIREDDY,BHOOMYREDDY,BHUMPALLI,BIJJAM,BIJJULA,BOBBILI,BODE,BOGALA,BOGGADI,BOJJIREDDY,BOKKA,BOLLA,BOLLAMPALLY,BOMMA,BOMMAREDDY,BOMMIREDDY,BOMMU,BONALA,BONDUGULA,BONTHU,BOTTA,BUCHEPALLI,BYREDDY,CHAMALA,CHADAA,CHAGANTI,CHALLA,CHALLAGONDA,CHAMAKURA,CHAVVA,CHEJARLA,CHIDIPUDI,CHILAKALA,CHINTHA,CHINTAREDDY,CHIRASANI,CHIRALA,CHANDIRI,CHANDUPATLA,CHEMARLA,CHEERLA,CHELAMALLA,CHENNAREDDY,CHERUKUPALLY,CHEREDDY,CHILAMAKURI,CHILUMULA,CHIRRA,CHIRLA,CHINEPALLI,CHINNAM,CHINTAKUNTA,CHINTALAPANI,CHINTAPALLY,CHINTHALAPALLI,CHINTHALAPANI,CHIRREDDY,CHITTAMURU,CHOLLETI,DABBALA,DADANA,DADITHOTA,DAGUMATI,DAMERA,DALLI,DANDA,DANGATLA,DARAM,DARGULA,DASARI,DEREDDY,DESAI,DESIREDDY,DEVA,DEVAGIRI,DEVARAPALLI,DEVAREDDY,DEVARENTI,DEVIREDDY,DIRISENAM,DODDA,DOKURU,DONTHI,DORASILA,DORNALA,DUBBA,DUGGIMPUDI,DUGGIREDDY,DUMPA,DWARAMPUDI,EDARA,EDDULA,EDULAKANTI,EDLA,EIPPALA,ELLAMLA,EMMADI,ENUGALA,ENUGU,EPURU,ERASANI,ESANAKULA,EVURI,GADDAM,GADDAMEEDI,GADE,GALI,GANDHARI,GANGASANI,GANGAVARAPU,GANGIDI,GANGIREDDY,GAJJALA,GANGUMALLA,GANNEPALLY,GANTA,GANDLA,GANDRA,GANTALA,GANUTHULA,GARLAPATI,GAVIREDDY,GAYAM,GEETLA,GOGIREDDY,GOLI,GONGIREDDY,GOODA,GOPIDI,GOPIREDDY,GOPU,GORLA,GORUSU,GOSULA,GOTTUMUKKULA,GOWRAVARAM,GUDA,GUDI,GUDDETI,GUDIGOPURAM,GUDIMETLA,GUDIPATI,GUJJULA,GUMMADI,GUNAPATI,GUNDALA,GUNDANNAGARI,GUNDAVARAPU,GUNNA,GUNNAM,GUNNAPAREDDY,GUNTA,GUNTAKA,GUNTUKA,GURIJALA,GURRALA,GURRAM',
    'Andhra Pradesh')

# Source 2: tgreddyyouth.wordpress.com
add_source('Reddy', 'https://tgreddyyouth.wordpress.com/reddy-gothrams/',
    'AALURI,ABBIDI,ABBIRREDDY,ADLA,ADMA,AEMALLA,AGUMAAMIDI,AIREDDY,AILENI,AKAVARAM,AKARAPU,AKKAPALLI,AKKATI,ALAVALA,ALLA,ALLADA,ALETI,ALLAM,AMBATI,AMARAM,ANANTULA,ANDEM,ANGANAGARI,ANIREDDY,ANKIREDDY,ANNADI,ANNAPAREDDY,ANNAREDDY,ANUMANDLA,ANUMULA,ANUPATI,APPANNAGARI,ARIMANDA,ARUMALLA,ARUTLA',
    'Andhra Pradesh, Telangana')


# ═══════════════════════════════════════════════════════════════════════════
# BRAHMIN SOURCES
# ═══════════════════════════════════════════════════════════════════════════

# Source 1: manatelugu.weebly.com
add_source('Brahmin', 'http://manatelugu.weebly.com/telugu-brahmins-family-names.html',
    'ADAALATU,ADUKURI,AINAPARTI,AINAMPROLU,AKHANDAM,ALAPATTU,ALETI,ALLADI,AMBADASU,AMBARUKHANA,AMRUTHAVAKKULA,ANANTAVARAPU,ANDUKURU,ANIPEDDI,ANNAVARPU,ANUMARLAPUDI,ATTOTA,ATREYAPURAPU,AYINAMBROLU,AYINPURA,AYYAGARI,BENDAPUDI,BIRUDAVOLU,BOLLAPRAGADA,BHAVARAJU,BHIMAVARAPU,BUDHARAJU,CHAGANTY,CHALLA,CHAKILAM,CHERUKU,CHILLARA,CHITRAPU,CHITTEM,DUBAGUNTA,DURGARAJU,DAMERLA,DESIRAJU,EDLAPALLI,EEDUPALLI,ERANKI,ERRAPATRUNI,ERRAPRAGADA,GANGARAVULA,GAMPA,GATRAJU,GADDAPALLI,GADIDASU,GANAPATIRAJU,GANUGAPATI,GAJULAPALLI,GADICHARLA,GHALI,GORIJAVOLU,JEEDIGUNTA,JOSYULA,KANCHIKACHARALA,KANCHUGANTALA,KATHARI,KANAKABHATTULA,KAVULU,KAVULURI,KAKARLAPUDI,KAKARLAMUDI,KAMARAJU,KANUKOLLU,KARINAPATI,KARLAPUDI,KASARABADA,KESHARAJU,KOOCHI,KOTAMRAJU,KOMARAVOLU,KORLIMARLA,KUPPILA,KHANDALADINNE,LAKKARAJU,MANNAVA,MOCHERLA,MATUKUMALLI,MUKKAPATI,MYLAVARAPU,NADIMPALLI,NEDUNURI,NISSANKALA,PALEPU,PARIMI,PARUPUDI,POTULA,PORURI,REGADAMILLI,RAYABHARAM,RUPANAGUNTA,SRIKARAM,SANDEPUDI,SAMPATAM,SAMBARAJU,SAMBATUR,SATTENAPALLI,SATRAM,SANNIKANDLAPADU,SAMUDRAM,SARIPALLI,SAVIDI,SOMAASI,STHAANAM,TAMMERA,TOLETI,TORTHI,TWARAKAVI,UDAYAGIRI,ULLAGANTI,UPPALA,URAKARANAM,VADDIRAJU,VADDURI,VADLAMUDI,VADURI,VALLAMBHATLA,VALLURI,VANAM,VANGIPURAPU,VONKAMAMIDI,VANKESWARAPU,VARAGANI,VARAHAGIRI,VARESWARAM,VARKHOLA,VASA,VASIRAJU,VELADI,VELAGAPUDI,VEPACHEDU,VISSAMRAJU,ABBURI,ACHANTA,ADDANKI,ADIMULAM,ADIRAJU,ADITHAM,ADIVI,ADURI,AJJARAPU,AKKANAPRAGADA,AKKINAPRAGADA,AKKENAPRAGADA,AKKARAJU,AKKINEPALLI,AKKIRAJU,AKUNURI,ALURU,AMANCHERLA,ANDUKURI,ANNAPRAGADA,ANNAMRAJU,ANNAVARAM,ARADHYULA,ARJARAPU,AVATAPALLI,AYYADEVARA,AYYAGARI,AYYALARAJU,BAKARAJU,BALABHADRAPATRUNI,BALANTHRAPU,BALEMARTHY,BALIVADA,BALLIJEPALLI,BAPATLA,BHADRIRAJU,BHARATHAM,BHATTIPROLU,BHOGARAJU,BHOGRAJ,BHUPATIRAJU,BITRAGUNTA,BODAPATI,BOLLAPRAGADA,BONDALAPATI,BOYINEPALLI,BUDDHAVARAPU,BUDHIRAJU,BUDARAJU,CHADHALAWADA,CHAKILAM,CHALLA,CHALLAPALLY,CHAMARTHY,CHANDARLAPATI,CHATRATHI,CHAMARAJU,CHEEMALAMARRI,CHENNAPRAGADA,CHILAKALAPUDI,CHIMAKURTHY,CHINTA,CHINTAPALLI,CHITTAMURI,CHORAGUDI,CHITRAPU,CHITTURI,CHODAVARAPU,DAMARAJU,DAMMALAPATI,DANAM,DESABHATLA,DESIRAJU,DEVARABHOTLA,DEVULAPALLI,DINAVAHI,DODDAVARAPU,DRONAMRAJU,DUGGARAJU,DUGGIRALA,ENJETI,GADE,GADIRAJU,GADDAMANUGU,GANDAVARAPU,GANGARAJU,GANJAM,GOLLAMUDI,GOLLAPUDI,GOPARAJU,GOTETI,GOVINDARAJU,GUDIPATI,GUDLADONA,GUDLAVALLETI,GUNDIMEDA,GUNDLAPALLI,GUNDAMARAJU,GUNNIKUNTLA,GURAZADA,IDURI,INUGURTHI,INUMELLA,IPPAGUNTA,IRAGAVARAPU,IVATURI,JAKKARAJU,JEEDIGUNTA,JONNALAGEDDA,JAYAGIRI,KAASIRAJU,KALAPATAPU,KALIGOTLA,KALUGOTLA,KADAMBARI,KAMAKOLANU,KAMBHAMMETTU,KANALA,KANCHNEPALLI,KANDUKURI,KANUKOLLU,KANUKOLANU,KANUPARTHY,KARAVADI,KARANAM,KASAVARAJU,KASTURI,KASUKURTHI,KAVI,KALLAKURI,KESINAPALLI,KOCHERLAKOTA,KODURI,KOKA,KOLANU,KOMARAVOLU,KONA,KONDA,KONDEPUDI,KONDAPALLY,KONDURI,KONDURU,KONIDENA,KORIMILLI,KORRAPATI,KORUPOLU,KOTAMRAJU,KOTAMARTHI,KOTARU,KOTHARU,KOTICHINTALA,KOVURU,KROVVIDI,KUMMAMURU,KURAPATI,LAKKAPRAGADA,LAKKARAJU,LAKKAVAJJULA,LINGAMGUNTA,MACHAVARAM,MACHIRAJU,MADDALI,MADIRAJU,MALKAPURAM,MALLAPRAGADA,MALYALA,MANAPRAGADA,MANCHIKALAPATI,MANCHIKANTI,MANCHIRAJU,MANDAPATI,MANGU,MANNAVA,MANTRI,MANTRIPRAGADA,MARAMRAJU,MARELLA,MARRIPATI,MATTIGUNTA,MATUKUMALLI,MEDIKONDURU,MITTAGUNTA,MOOPARTI,MOORTHIRAJU,MUKKAMALA,MULAKALURI,MULUGU,MULPURI,MUNIMANIKYAM,MUNIPALLE,MUPPALLA,MYNAMPATI,MYLAVARAPU,NADELA,NAMBURI,NANDANAVANAM,NANDIWADA,NANDURI,NARAPARAJU,NADIMPALLI,NAVULURI,NEELAMRAJU,NELLUTLA,NEMALIKANTI,NIDAMARTHI,NIMUSHAKAVI,NIMISHAKAVI,NISSANKALA,PABBARAJU,PAGOLU,PALAKODETY,PALIVELA,PALUTLA,PAMULAPARTHI,PAMULAPATI,PANAMGIPALLI,PANCHALAVARAPU,PANGULURI,PANTHANGI,PARAMATMUNI,PARAMKUSHAM,PARIMI,PEGATRAJU,PATHIKONDA,PEMMARAJU,PENAMAKURU,PENUMUDI,PERALA,PETLURI,PINGALI,PILLUTLA,PIDURU,PINDIPROLU,POCHIRAJU,PODURI,POOLLA,POLAMRAJU,POLAVARAM,POLURI,PONDURI,PONNADA,PORURI,POTHAPRAGADA,POTHARAJU,POTTURI,PRAGADARAJU,PULIJALA,PULIKANTI,PULIPAKA,PULLAMARAJU,PUNYAMURTHULA,PUTTABAKULA,PUVVADA,RACHAPUDI,RACHERLA,RAJASEKHARUNI,RAMAJARU,RAMARAJU,RANGARAJU,RAVINUTALA,RAVULAPARTI,RAVURI,RUPANAGUNTA,SAMBHARAJU,SANDEPUDI,SANTAPUR,SAMBATUR,SARRAJU,SARIKONDA,SARVEPALLI,SATTIRAJU,SAATHAMRAJU,SATYAVOLU,SEETHAMRAJU,SEETHIMRAJU,SIDDIRAJU,SINGAM,SINGAMPALLI,SINGARAJU,SIRIPURAPU,SURAPARAJU,TADANKI,TADAKAMALLA,TADIKONDA,TALLAPRAGADA,TALLAMRAJU,TALLURI,TANUKU,TAMVADA,TANGUTURI,TADINADA,TADIMETI,TAMIRISA,TATAVARTHY,TETALI,THUNGATHURTHI,TUMMURUGOTI,TIMMARAJU,TURAGA,TVARAKAVI,TURLAPATI,UNNAVA,UPPALURI,VADDADI,VADLAMANNATI,VADREVU,VALLURI,VAJJA,VAKKALANKA,VANGIPURAPU,VANKAMAMIDI,VARANASI,VARAHAGIRI,VEDAGIRI,VEDURURU,VELADI,VELAGAPUDI,VELAPARTI,VELDURTHY,VELICHETY,VEMPATI,VEMULA,VEMULAKONDA,VEMURI,VENTRAPRAGADA,VENUTURUPALLE,VEPAKOMMA,VIRIYALA,VOLETY,VURAKARANAM,WURITI,YABALOORI,YALLAPRAGADA,YANDAPALLI,YARRAPRAGADA,YEDIDA,YENDLURI,YERRAMILLI,YERRAPRAGADA,YEDDANAPUDI,WUPPALAPATI,UPPALAPATI',
    'Andhra Pradesh')


# ═══════════════════════════════════════════════════════════════════════════
# VYSYA SOURCES
# ═══════════════════════════════════════════════════════════════════════════

# Source 1: saumyakotha.blogspot.com
add_source('Vysya', 'http://saumyakotha.blogspot.com/2011/10/arya-vysya-surnames.html',
    'AAGUDOTA,AAGURI,AALAMURI,AALAPATI,ADDAGIRI,ADDEPALLY,ADIMULAM,AGER,AGGARWAL,AGIR,AITHA,AKKENAPALLY,AKKINAPELLI,AKULA,AKUTHOTA,ALAMPALLY,ALAVALA,ALIGARI,ALLAGADDA,AMARA,AMBATI,ANATHAPALLI,ANOOR,ANUMALA,ANUMULA,ARAVETI,ARISETTY,ARVAPALLI,ARVETI,ATMAKOORU,ATTULURI,ATTULURU,ATYAM,BACHA,BACHU,BADAM,BAISANI,BAJJURI,BALABADHRUNI,BALABHADRAPU,BALANAGU,BANGARU,BATCHU,BATTEPATI,BAVIRISETTY,BEJGUM,BEJUGAM,BELDE,DEVATHA,BHAVANASI,BHEERAVELLI,BHUMA,BHUPATHI,BILLAPATI,BITTA,BIYYAPU,BODLA,BOGAPENTAM,BOGGARAPU,BOGGAVARAPU,BOLISETTY,BOLLISETTY,BOMMERLA,BOMMISETTY,BONDA,BONDADA,BUDDA,BUDHAGUTA,BUDLA,BUKKABANDI,BURUGU,BUSETTY,BUSSA,BYRISETTY,BYSANI,CHAKKA,CHALLA,CHAMARTHY,CHANDA,CHANDALURI,CHANDOLU,CHANDRAGUPTLA,CHATAKONDA,CHAVALA,CHAVVA,CHEBOLU,CHEDELLA,CHENNA,CHEPURI,CHEVURI,CHIKILAM,CHIKOTI,CHILUKURU,CHINTA,CHINTAGUNTA,CHIPPAGIRI,CHITLOORI,CHITLUR,CHITTIMELLI,CHITURI,CHODAVARAPU,CHOKKARAPU,CHOPPERLA,CHOVALA,CHUNDOORY,DACHEPALLY,DAMERA,DANTI,DASARI,DEEKONDA,DESU,DEVAKI,DEVARAPALLI,DEVARASETTY,DEVATHI,DEVUNURI,DHARA,DIDIGAM,DINTHAKURTHY,DODDA,DOKUPARTHI,DONTHULA,DONTI,DONTULA,DORNADULA,DOSAPATI,DOSARLAPATI,DUDDU,DUNDUKURTHI,DURGA,EKKETI,EPURI,EPURU,ERUKULA,GAARLA,GADEMSETTY,GADEY,GADHAMSHETTY,GAJJALA,GAJJELA,GAMPA,GANDE,GANDHAM,GANGISETTY,GANGISHETTY,GANJI,GANNU,GARALA,GARIPALLY,GARLA,GARUDA,GATTU,GELIVI,GHANTASHALA,GOKAVARAPU,GOLLA,GOPARAPU,GOPU,GOURISHETTY,GRANDHE,GRANDHI,GUBBOLU,GUDALA,GUDISHETTY,GUDIVADA,GUDUR,GULBAM,GUNDA,GUNDU,GUNIPUTI,GUNTA,GUNTHA,GUNTUR,GUNTURU,GURUDU,IMMIDI,IMMIDISETTY,INNAMURI,ITIKALA,JAGGAVARAPU,JAINI,JALADI,JALLIPALLI,JALLURI,JALUMURI,JAMMISETTY,JANUMPALLI,JAYAVARAM,JAYAVARAPU,JILLA,JOOLURI,JULAKANTI,JULURI,JUPUDY,JUTURU,KADIMISETTY,KALAKOTAWAR,KALAMADI,KALIKI,KALLALURI,KANAKATALA,KANAMARALAPUDI,KANCHARLA,KANCHERLA,KANDE,KANDEPI,KANDIKONDA,KANDUKURI,KANDURU,KANICHETTY,KANKANWAR,KANNAN,KANUMURI,KAPAGANTY,KAPARTI,KARAMSETTY,KARLAPATI,KARNATAKAM,KARNATI,KARRA,KARUMURI,KASAM,KASAMSETTI,KASANGOTTUWAR,KASTURI,KASULA,KATAKAM,KATEPALLY,KAULWAR,KEDARISETTI,KELIGARI,KESANAPALLI,KETHEPALLI,KEYAN,KODTHALA,KODUMURI,KODURI,KOKKALA,KOLETI,KOLIPAKULA,KOLLEPARA,KOLLI,KOLLURU,KOMIRISHETTY,KOMMA,KOMMURI,KONAGELLA,KONAKALLA,KONDA,KONDARACHOTI,KONDOORI,KONDURU,KONIJERLA,KONIJETI,KOPPARAPU,KOPPURAVARI,KORA,KOTA,KOTHA,KOTLA,KOTRIKE,KOTTHAMASU,KOUKUNTLA,KUKUTAM,KUNALA,KUNCHAKURA,KUNISETTY,KURAKU,KURELLA,KURISETI,KUSUMANCHI,LABISHETTY,LAGGISETTY,LAGHUVARAPU,LAGUSETTI,LAVISHETTY,LINDAKURTHY,LINGA,MAALE,MACHA,MACHEPALLI,MADALAM,MADAM,MADDALA,MADDI,MADDU,MADDULA,MADEM,MADHARAPU,MADISHETTY,MAGALURI,MAHANKALI,MAJETY,MAKAM,MAKKALA,MALIPEDDI,MALLEMKONDU,MALLISETTI,MAMIDI,MAMIDIPAKA,MANASANI,MANCHALA,MANCHIKANTA,MANCHIKANTI,MANCHUKANTI,MANCHUKONDA,MANDAVALLI,MANEPALLI,MANGALAGIRI,MANIKONDA,MANNEM,MARAM,MARYALA,MATCHA,MATOORI,MATTA,MATTEY,MATTUPALLI,MAVIDADA,MEDA,MEDAM,MEDASEGU,MENTA,METUKU,MIDIDUDDI,MIRYALA,MITTA,MITTENTI,MODI,MOGULLAPALLY,MOPURU,MORISHETTI,MOTAMARRI,MUCHERLA,MUGHAN,MUKKA,MUMMADI,MURAHARI,MUTTA,NAGAMALLA,NAGARAKANTI,NAGELLA,NAGULU,NAGUMILLI,NAGUNOORI,NAGUNURI,NALAM,NAMA,NAMBOORI,NAMBURU,NANGARI,NANGUNOOR,NARASHINOLU,NARAYANA,NARAYANAM,NARENDRUNI,NATAKALA,NATHA,NEELISETTY,NEERUMALLA,NERELLA,NETHI,NOMULA,NOOKA,NOOKALA,NOONEY,NUKA,NULI,OBULASETTY,PABBA,PABBATI,PACHIPULUSU,PADMANABHAM,PADMANABHUNI,PADUCHURI,PADUCHURU,PALAKURTHI,PALEMPALLI,PALEPU,PALIVELA,PALUCHURI,PANDIRI,PARUCHURU,PARUKOTI,PASPUNOORI,PASUPARTHI,PASUPULA,PATCHIGOLLA,PATCHIPULUSU,PATHA,PATTAM,PEDDI,PENDEKANTI,PENDYALA,PENJURI,PENJURU,PENTAPATI,PENUGONDA,PERLA,PERUMELLA,PERURI,PETTUGANI,PIPPALLA,PODDATUTI,POKALA,POLA,POLAVARTHI,POLISETTY,POLURI,POTTA,POTTI,PRATHI,PRODATTORI,PUBBISETTY,PULAVARTHI,PULIGILLA,PULIPATI,PULLURI,PUSARLA,PUTTA,PUVVADA,PYDAH,RACHAMALLA,RACHAPALLI,RAJA,RAJANAHALLI,RAMINI,RANGA,RAVIKANTI,RAVULA,REPAKULA,REVERU,RUDRAVARAM,SABBISETTY,SAGUTURU,SAJJANSHETTY,SAMPARTHI,SAMRAT,SAMUDRALA,SANISETTY,SANKA,SATYAVARAPU,SEEMAKURTHY,SHARVIRALA,SHEELA,SHIRAHATTI,SHIVAKOTI,SIMHADRI,SINGAMSETTY,SINGAMSHETTY,SINGANAMALA,SIRIGINEEDI,SITIRALA,SIVVA,SOLLETI,SOMA,SOMISETTY,SOMOSETTY,SOMU,SONNATHY,SOORAVARAPU,SRIPATHI,SUNKU,SURAMPALLI,SURPUR,SUTHAPALLI,TADIKAMALLA,TADIKONDA,TADUVOYI,TALLAM,TANGUTOORI,TAVVA,TELIGUNTA,TELUKUNTA,TELUKUNTLA,TERATAPALLY,THATIKONDA,THIRIVEEDU,THOMMANDRU,THUDUPUNOORI,THUMMALAPALLI,THUMPUDI,TIRUMALA,TONTEPU,TOPAJI,TULABANDHULA,TUNUGUNTLA,UPPALA,UPPALANCHA,UTUKURI,VABILISETTI,VADAKATTU,VAKACHARLA,VAKATI,VALIVETI,VALLAMKONDU,VALLAMSHETTY,VANAMA,VANDANAPU,VANKADAR,VANKADARI,VANKAYALA,VARIGALA,VELURI,VELURU,VELVALURI,VEMULA,VEMURI,VENISHETTY,VETSA,VISHWANATHAM,VOBATTU,VOBILISETTI,VOLAM,VOLETI,VOLLALA,VOORA,VUDATHU,VUPPALA,VUSTEPALLI,VUYYALA,VYAMASANI,WATTAMWAR,YADA,YADALAM,YAKKALA,YAMA,YEKKALA,YELAMARTHI,YELCHURI,YELISETTI,YELLORU,YERRAM,YERRAMSETTY,ZAKKAM',
    'Andhra Pradesh')


# ═══════════════════════════════════════════════════════════════════════════
# KAPU SOURCES
# ═══════════════════════════════════════════════════════════════════════════

# Source 1: kapucommunity.com
add_source('Kapu', 'https://kapucommunity.com/surnames-and-gotralu',
    'ARAKALA,ATTADA,AANALA,ABBISETTI,ACHUKOLA,ADABALA,ADAGARLA,ADAPA,ADATRA,ADDAGARLA,ADDAGIRI,ADDALA,ADDANKI,ADDEPALLI,ADIKAARI,AGARAM,AKAM,AKASAPU,AKETI,AKKALA,AKKIREDDI,AKKISETTY,AKULA,ALAHARI,ALAJANGI,ALAMURI,ALLADA,ALLADI,ALLAM,ALLAMSETTY,ALLU,ALUVALA,AMANCHI,AMBARAPU,AMBULA,ANDE,ANDEY,ANGADI,ANIMADUGULA,ANISETTI,ANKAM,ANNABATTULA,ANNAM,ANNAMREDDY,ANNANGI,ANNAPAREDDI,ANRAJULA,ANUGULA,ANUMAKONDA,APPAPANTULA,APPIKATLA,ARANI,ARISETTY,ARIGELA,ARISANKALA,ARJIPU,ARZA,ASULA,ATHILI,ATHMURI,AVALA,AVULA,AYINALA,AYYA,BADAM,BADARLA,BADE,BADETI,BADIREDDI,BAIREDDY,BAISETTI,BAKI,BALAGAM,BALISETTY,BALLEM,BALLA,BALU,BANALA,BANDARU,BANDE,BANDI,BANDREDDI,BANTROTU,BAREGALA,BARLA,BARLAPUDI,BARMA,BASAVA,BASU,BATCHU,BATHINA,BATTINI,BATTULA,BEESABATHUNI,BEJJAM,BELLAPU,BESABATTINI,BETHAMCHERLA,BETHAMSETTY,BETHI,BETHU,BEVARA,BHADRI,BHIMA,BHOGADI,BHUPATHI,BHUVANESWARAM,BILLAKANTI,BILLINGI,BIRUDA,BOBBILI,BODAPATI,BODDAPU,BODU,BOGIREDDY,BOKKISAM,BOLISETTY,BOLLA,BOLLAM,BOMMASANI,BOMMISETTY,BOMMU,BONAM,BONDA,BONDADA,BONGARALA,BONTHA,BONTHULA,BOPPA,BORA,BORRA,BORUSU,BOTSA,BOYINA,BRUNDAVANA,BUDDALA,BUDIM,BUNA,BURAGADDA,BYRISETTY',
    'Andhra Pradesh')

# Source 2: kapucaste-origins.blogspot.com (already scraped)
# Already have this data from earlier runs


# ═══════════════════════════════════════════════════════════════════════════
# SC SOURCES (Mala, Madiga)
# ═══════════════════════════════════════════════════════════════════════════

# From Wikipedia and government lists
add_source('SC', 'https://en.wikipedia.org/wiki/Mala_(caste)',
    'MALA,DASARI,MADIGA,POLU,PEDDI,MEKALA,MADALA,GADDAM,MALLELA,DHANASARI,DHANISIRI,TELLAMEKALA,SARAMEKALA,BUDDI,BONAM,DEEPALA,NEELI,NEELAM,AMUDALA,MASARAPU,AVUTHU,BURRAMUKKU,MOSALA,PODILE,TULASI,MUTYALA,MYLA,LEKKALA,VADDE,CHILAKA,MAILA,BHIMANA',
    'Andhra Pradesh')


# ═══════════════════════════════════════════════════════════════════════════
# BUILD AND SAVE
# ═══════════════════════════════════════════════════════════════════════════

def main():
    # Deduplicate: same surname from same source
    seen = set()
    unique = []
    for entry in CORPUS:
        key = (entry['surname'], entry['caste'], entry['source_url'])
        if key not in seen:
            seen.add(key)
            unique.append(entry)

    # Count per caste
    from collections import Counter
    caste_counts = Counter(e['caste'] for e in unique)

    print(f"Ground Truth Corpus Built")
    print(f"{'='*50}")
    print(f"Total unique entries: {len(unique):,}")
    print(f"Unique surnames: {len(set(e['surname'] for e in unique)):,}")
    print(f"\nBy caste:")
    for caste, count in caste_counts.most_common():
        sources = len(set(e['source_url'] for e in unique if e['caste'] == caste))
        print(f"  {caste:<15} {count:>6,} entries from {sources} sources")

    # Find surnames in multiple castes
    surname_castes = defaultdict(set)
    for e in unique:
        surname_castes[e['surname']].add(e['caste'])
    multi = {s: castes for s, castes in surname_castes.items() if len(castes) > 1}
    print(f"\nSurnames appearing in multiple castes: {len(multi)}")
    for s, castes in sorted(multi.items(), key=lambda x: -len(x[1]))[:20]:
        print(f"  {s:<25} {', '.join(sorted(castes))}")

    # Save
    output = os.path.join('data', 'surname_ground_truth.csv')
    with open(output, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['surname', 'caste', 'source_url', 'gothram', 'region', 'example_full_names'])
        for e in sorted(unique, key=lambda x: (x['caste'], x['surname'])):
            writer.writerow([e['surname'], e['caste'], e['source_url'], e['gothram'], e['region'], ''])

    print(f"\nSaved to {output}")


if __name__ == '__main__':
    main()
